version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - GROQ_API_KEY=${GROQ_API_KEY}
    command: >
      sh -c "until nc -z db 5432; do echo 'Waiting for DB...'; sleep 2; done &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  db:
    image: pgvector/pgvector:pg15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    env_file:
      - .env

volumes:
  postgres_data:
